export const DEVICE_FIELDS = {
  fields: [
    { key: 'name', alias: '名称', group: 'basic', visible: true },
    { key: 'type', alias: '类型', group: 'basic', visible: false },
    { key: 'label', alias: '标签', group: 'basic', visible: false },
    { key: 'active', alias: '在线', group: 'status', visible: true },
    { key: 'lastActivityTime', alias: '最后活动时间', group: 'status', visible: false },

    { key: 'DeviceNo', alias: '设备编号', group: 'device', visible: true },
    { key: 'MQTT_CLIENT_ID', alias: 'MQTT客户端ID', group: 'device', visible: false },
    { key: 'credentialsValue', alias: '鉴权信息', group: 'device', visible: false },
    { key: 'DeviceName', alias: '设备名称', group: 'device', visible: false },
    { key: 'DeviceType', alias: '设备类型', group: 'device', visible: false },
    { key: '监测类型', alias: '监测类型', group: 'device', visible: false },
    { key: 'manufacturer', alias: '制造商', group: 'device', visible: false },
    { key: 'ower', alias: '所有者', group: 'device', visible: true },
    { key: 'project', alias: '所属项目', group: 'device', visible: true },

    { key: 'ProviceNo', alias: '省份编号', group: 'site', visible: true },
    { key: 'city', alias: '城市', group: 'site', visible: true },
    { key: 'county', alias: '县区', group: 'site', visible: true },
    { key: 'town', alias: '乡镇', group: 'site', visible: false },
    { key: 'village', alias: '村庄', group: 'site', visible: false },
    { key: 'StationNo', alias: '站点编号', group: 'site', visible: true },
    { key: 'StationName', alias: '站点名称', group: 'site', visible: true },
    { key: 'location', alias: '位置', group: 'site', visible: false },
    { key: '灾害类型', alias: '灾害类型', group: 'site', visible: false },
    { key: '建设级别', alias: '建设级别', group: 'site', visible: false },
    { key: '建设年份', alias: '建设年份', group: 'site', visible: false },

    { key: 'Longitude', alias: '经度', group: 'geo', visible: false },
    { key: 'Latitude', alias: '纬度', group: 'geo', visible: false },
  ],
  order: [
    'name',
    'StationName',
    'active',
    'DeviceNo',
    'credentialsValue',
    'ower',
    'project',
    'ProviceNo',
    'city',
    'county',
    'StationNo',
    'type',
    'label',
    'lastActivityTime',
    'DeviceName',
    'DeviceType',
    '监测类型',
    'manufacturer',
    'town',
    'village',
    'location',
    '灾害类型',
    '建设级别',
    '建设年份',
    'Longitude',
    'Latitude',
  ],
  groups: {
    basic: { title: '基础信息', order: ['name', 'type', 'label'] },
    status: { title: '状态信息', order: ['active', 'lastActivityTime'] },
    device: {
      title: '设备信息',
      order: [
        'DeviceNo',
        'DeviceName',
        'DeviceType',
        'credentialsValue',
        '监测类型',
        'manufacturer',
        'ower',
        'project',
      ],
    },
    site: {
      title: '站点与建设信息',
      order: [
        'ProviceNo',
        'city',
        'county',
        'town',
        'village',
        'StationNo',
        'StationName',
        'location',
        '灾害类型',
        '建设级别',
        '建设年份',
      ],
    },
    geo: { title: '地理坐标', order: ['Longitude', 'Latitude'] },
  },
};

export const ASSET_FIELDS = {
  fields: [
    { key: 'name', alias: '名称', group: 'basic', visible: true },
    { key: 'type', alias: '类型', group: 'basic', visible: false },
    { key: 'label', alias: '标签', group: 'basic', visible: false },

    { key: '省级编号', alias: '省级编号', group: 'site', visible: true },
    { key: '监测点编号', alias: '监测点编号', group: 'site', visible: true },
    { key: '监测点名称', alias: '监测点名称', group: 'site', visible: true },
    { key: '市', alias: '市', group: 'site', visible: true },
    { key: '县（市、区）', alias: '县（市、区）', group: 'site', visible: true },
    { key: '乡（镇、街道）', alias: '乡（镇、街道）', group: 'site', visible: true },
    { key: '村（居）', alias: '村（居）', group: 'site', visible: true },
    { key: '地理位置', alias: '地理位置', group: 'site', visible: false },

    { key: '灾害类型', alias: '灾害类型', group: 'hazard', visible: false },
    { key: '隐患区域地形地貌名称', alias: '隐患区域地形地貌名称', group: 'hazard', visible: false },
    { key: '是否隐患点', alias: '是否隐患点', group: 'hazard', visible: false },
    { key: '隐患点状态', alias: '隐患点状态', group: 'hazard', visible: false },

    { key: '建设级别', alias: '建设级别', group: 'construction', visible: true },
    { key: '建设单位', alias: '建设单位', group: 'construction', visible: true },
    { key: '建设年份', alias: '建设年份', group: 'construction', visible: true },
    { key: '是否改建点', alias: '是否改建点', group: 'construction', visible: false },
    { key: '改建年份', alias: '改建年份', group: 'construction', visible: false },
    { key: '项目', alias: '建设项目', group: 'construction', visible: true },

    { key: '经度', alias: '经度', group: 'geo', visible: false },
    { key: '纬度', alias: '纬度', group: 'geo', visible: false },
    { key: '高程', alias: '高程', group: 'geo', visible: false },

    { key: '威胁户数（户）', alias: '威胁户数（户）', group: 'stats', visible: false },
    { key: '威胁人数（人）', alias: '威胁人数（人）', group: 'stats', visible: false },
    { key: '威胁财产（万元）', alias: '威胁财产（万元）', group: 'stats', visible: false },

    { key: 'relateYL', alias: '关联雨量', group: 'extra', visible: true },
    { key: '设备厂商', alias: '设备厂商', group: 'extra', visible: false },
    { key: '设立日期', alias: '设立日期', group: 'extra', visible: false },
    { key: '部平台同步时间', alias: '部平台同步时间', group: 'extra', visible: false },
  ],
  order: [
    'name',
    '监测点名称',
    '省级编号',
    '监测点编号',
    '项目',
    'relateYL',
    '市',
    '县（市、区）',
    '乡（镇、街道）',
    '村（居）',
    '建设级别',
    '建设单位',
    '建设年份',
    'type',
    'label',
    '地理位置',
    '灾害类型',
    '隐患区域地形地貌名称',
    '是否隐患点',
    '隐患点状态',
    '是否改建点',
    '改建年份',
    '经度',
    '纬度',
    '高程',
    '威胁户数（户）',
    '威胁人数（人）',
    '威胁财产（万元）',
    '设备厂商',
    '设立日期',
    '部平台同步时间',
  ],
  groups: {
    basic: { title: '基础信息', order: ['name', 'type', 'label'] },
    site: {
      title: '站点与位置',
      order: ['省级编号', '监测点编号', '监测点名称', '市', '县（市、区）', '乡（镇、街道）', '村（居）', '地理位置'],
    },
    hazard: { title: '隐患与灾害', order: ['灾害类型', '隐患区域地形地貌名称', '是否隐患点', '隐患点状态'] },
    construction: {
      title: '建设信息',
      order: ['建设级别', '建设单位', '建设年份', '是否改建点', '改建年份', '项目'],
    },
    geo: { title: '地理坐标', order: ['经度', '纬度', '高程'] },
    stats: { title: '威胁统计', order: ['威胁户数（户）', '威胁人数（人）', '威胁财产（万元）'] },
    extra: { title: '其他信息', order: ['relateYL', '设备厂商', '设立日期', '部平台同步时间'] },
  },
};
